apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-app
  spec:
  replicas: 3
selector:
  matchLabels:
    env: test-app
template:
  metadata:
    spec:
      name: tmp-01
      labels:
        env: dev
  spec:
    containers:
      - name: c1
        image: nginx
        ports:
          - containerPort: 80 
---
apiVersion: v1
kind: service
metadata:
  name: test-app-service
spec:
  selector:
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
